feature first commit
YuKanke/polifo2 pull request #1
Opened 2019-08-02 04:32 UTC by YuKanke

2019-08-02 15:12 UTC, akaa07 reviewed
以下にはファイルを手動で配置するべきではない。
- public/css/
- public/js/

Laravel Mixを使用した場合にファイルが消失する。
[アセットのコンパイル(Laravel Mix) 5.6 Laravel](https://readouble.com/laravel/5.6/ja/mix.html)

ファイル数が多いとページの読み込み時間等にも影響するため、Laravel Mixの使用を検討することを推奨する。

2019-08-02 15:12 UTC, akaa07 commented on app/Http/Controllers/PortfolioController.php
> +class PortfolioController extends Controller
class, methodともにphpdocを記載するべき。
コードを追わないと何をするためのclass, methodなのかがわからない

ex.
```
/**
  * ポートフォリオに関する処理を制御するクラス
  *
  * 照会は未ログイン状態でも可能。
  * 更新処理はログイン中のユーザのみ可能。
  */
```

2019-08-02 15:12 UTC, akaa07 commented on app/Http/Controllers/PortfolioController.php
> +    public function getImage(request $request){
class, methodともにphpdocを記載するべき。
コードを追わないと何をするためのclass, methodなのかがわからない

ex.
```
/**
  * 画面のスクリーンショットを保存して公開パスを返却します。
  *
  * @param  \Illuminate\Http\Request $request
  * @return string 画像ファイルの公開パス
  */
```

2019-08-02 15:12 UTC, akaa07 commented on app/Http/Controllers/PortfolioController.php
> +        $imageName = $fileDir . Auth::id() . '_image.png';
ログイン中であることを前提にAuthヘルパを使用する場合は、ミドルウェアで保護すること。

2019-08-02 15:12 UTC, akaa07 commented on app/Http/Controllers/PortfolioController.php
> +        $image = file_get_contents($baseUrl . $request->url . "?w=960&h=960", false, $ctx);
`$request->url`に対するバリデーションを実施すること。
FormRequestを使用することが望ましい。（FormRequestを使うことでバリデーションが実施されたことが担保され、リクエストレイアウトについても明確になる）

2019-08-02 15:12 UTC, akaa07 commented on app/Http/Controllers/PortfolioController.php
> +        $baseUrl = "https://s.wordpress.com/mshots/v1/";
URLは変更される可能性もあるので、configファイルに記載することが望ましい。
また、取得処理自体も変更される可能性がある or 他で類似処理をする可能性もあるため、別クラスに分けた方が良い。

2019-08-02 15:12 UTC, akaa07 commented on app/Http/Controllers/PortfolioController.php
> +        $image = file_get_contents($baseUrl . $request->url . "?w=960&h=960", false, $ctx);
`file_get_contents`ではなく`curl`の方がシンプルにかけるのでは？

2019-08-02 15:12 UTC, akaa07 commented on app/Http/Controllers/PortfolioController.php
> +        $fileDir = "images/";
動的に生成するファイルを`public`配下に保存する処理は非推奨。
`storage/app/public`に保存するようにするべき。
`public`配下はgit管理対象であり、ユーザが生成したデータを保管するとgitにゴミが混入する。

2019-08-02 15:12 UTC, akaa07 commented on app/Http/Controllers/PortfolioController.php
> +        file_put_contents($imageName, $image);
publicに配置することで、画像を保存したユーザ以外のユーザや未ログイン状態でも閲覧できてしまうが、想定通りか？

2019-08-02 15:12 UTC, akaa07 commented on app/Http/Controllers/PortfolioController.php
> +        file_put_contents($imageName, $image);
`file_put_contents`を使うよりLaravelのファイルストレージを利用する方がよいのでは？
[Laravel 5.6 ファイルストレージ](https://readouble.com/laravel/5.6/ja/filesystem.html)

2019-08-02 15:12 UTC, akaa07 commented on app/Http/Controllers/PortfolioController.php
> +        $imageName = $fileDir . Auth::id() . '_image.png';
ファイル名の重複などは、明確にコメントを残したほうが良い。
```
// 1ユーザ最大1件まで画像を保存可能
```

2019-08-02 15:12 UTC, akaa07 commented on app/Http/Controllers/PortfolioController.php
> +    public function list(){
テストのしやすさ等を考慮して、DIを使用したほうが良い。
```
public function list(Portfolio $portfolio){
}
```

2019-08-02 15:12 UTC, akaa07 commented on app/Http/Controllers/PortfolioController.php
> +    public function update(request $request){
FormRequestを使ったほうが良い。
DIを使用したほうが良い。

2019-08-02 15:12 UTC, akaa07 commented on app/Http/Controllers/PortfolioController.php
> +        $user = User::find(Auth::id());
Auth::user()と同義であるため、Auth::user()の方がよいのでは？

2019-08-02 15:12 UTC, akaa07 commented on app/Http/Controllers/PortfolioController.php
> +        $portfolio = Portfolio::firstOrNew(['user_id' => $user->id]);
こういう書き方の方がスマート
```
$portfolio = $user->portfolios()->firstOrNew();
```

2019-08-02 15:12 UTC, akaa07 commented on app/Http/Controllers/PortfolioController.php
> +        $user->name = $request->name;
複数モデルの更新時にはトランザクションを使用すること。

2019-08-02 15:12 UTC, akaa07 commented on app/Http/Controllers/PortfolioController.php
> +        $portfolio->url = $request->url;
`url`, `image`, `name`については、`App\Portfolio`にfillableを設定し、`$portfolio->fill(hoge)`を使用することを推奨する。

2019-08-02 15:12 UTC, akaa07 commented on app/Http/Controllers/UserController.php
> +    public function setting(){
Authミドルウェアを適用すること。

2019-08-02 15:12 UTC, akaa07 commented on app/Http/Controllers/UserController.php
> +        $categorys = Tag::select("category")->groupBy('category')->get();
`$categorys` → `$categories`

2019-08-02 15:12 UTC, akaa07 commented on app/Http/Controllers/UserController.php
> +        $categorys = Tag::select("category")->groupBy('category')->get();
groupByだと全件検索してしまうので、tagsテーブルとcategoriesテーブルを分割した方が良い

2019-08-02 15:12 UTC, akaa07 commented on config/BOTU_tag_list.php
> +<?php
不要ファイルであれば削除すること。

2019-08-02 15:12 UTC, akaa07 commented on database/migrations/2019_07_16_074107_create_portfolios_table.php
> +            $table->timestamps();
インデントを修正すること

2019-08-02 15:12 UTC, akaa07 commented on database/migrations/2019_07_16_074107_create_portfolios_table.php
> +		$table->integer('user_id');
1:1関係ならunique制約を付けるべき

2019-08-02 15:12 UTC, akaa07 commented on database/migrations/2019_07_19_024219_create_tags_table.php
> +            $table->timestamps();
インデントを修正すること

2019-08-02 15:12 UTC, akaa07 commented on database/migrations/2019_07_19_024219_create_tags_table.php
> +    }
`tag_name`と`category`は重複しないようにするためにunique制約をつけるのが望ましい

2019-08-02 15:12 UTC, akaa07 commented on database/migrations/2019_07_19_024253_create_portfolio_tag_table.php
> +            $table->timestamps();
インデントを修正すること

2019-08-02 15:12 UTC, akaa07 commented on routes/web.php
> +Route::get('/list', 'PortfolioController@list');
リソースコントローラの使用を検討することを推奨する。
[コントローラ 5.6 Laravel](https://readouble.com/laravel/5.6/ja/controllers.html#resource-controllers)

2019-08-02 15:14 UTC, akaa07 commented
全般的にコメントが少ない。昨日の自分は他人だと思ってコメントを記載するようにすること。
適切なコメント量の目安は、処理の流れを目で追わずに流し読みで処理内容が理解できる程度。

2019-08-02 15:15 UTC, akaa07 commented
README.mdはメンテしたほうが良い。
このプロジェクトは何を目的としているのか？何を実現するのか？が書いてあるとサービス設計の軸がぶれにくくなる。

2019-08-02 15:17 UTC, akaa07 commented
プルリクエストのマージ先が間違っている。
`develop`が正しいマージ先。`develp` → `master`へのマージは、アプリをリリースしたタイミングで行う。

2019-08-02 15:19 UTC, akaa07 commented
テストコードがない

2020-03-05 00:32 UTC, ecbeing-internalSystem approved these changes

2020-03-05 00:34 UTC, ecbeing-internalSystem requested changes
ok

2020-03-05 00:36 UTC, ecbeing-internalSystem requested changes
ok

2020-03-05 00:39 UTC, merged